import { YocoolabApiClient } from '../api-client.js';
import { GitHubClient, FileChange } from '../github-client.js';
import type { ThreadUpdateEmitter } from '../http-bridge.js';

const FIXES_END_MARKER = '<!-- YOCOOLAB_FIXES_END -->';

function buildInitialPrBody(
  repoFullName: string,
  threadId: string,
  title: string,
  commitSha: string,
  parentContext?: string
): string {
  const parts = [
    `## Yocoolab Feedback Fixes`,
    ``,
    `This PR collects AI-generated fixes for feedback threads on \`${repoFullName}\`.`,
    ``,
  ];

  if (parentContext) {
    parts.push(parentContext, ``);
  }

  parts.push(
    `### Fixes`,
    ``,
    `| # | Thread | Description | Commit |`,
    `|---|--------|-------------|--------|`,
    `| 1 | \`${threadId.slice(0, 8)}\` | ${title} | [\`${commitSha.slice(0, 7)}\`](https://github.com/${repoFullName}/commit/${commitSha}) |`,
    FIXES_END_MARKER,
    ``,
    `---`,
    `*Auto-generated by Yocoolab AI. Updated as new fixes are added.*`,
  );

  return parts.join('\n');
}

function appendFixToPrBody(
  existingBody: string,
  repoFullName: string,
  fixNumber: number,
  threadId: string,
  title: string,
  commitSha: string
): string {
  const newRow = `| ${fixNumber} | \`${threadId.slice(0, 8)}\` | ${title} | [\`${commitSha.slice(0, 7)}\`](https://github.com/${repoFullName}/commit/${commitSha}) |`;

  if (existingBody.includes(FIXES_END_MARKER)) {
    return existingBody.replace(FIXES_END_MARKER, `${newRow}\n${FIXES_END_MARKER}`);
  }

  // Fallback: append to the end
  return existingBody + '\n' + newRow;
}

export async function handleCreatePr(
  api: YocoolabApiClient,
  github: GitHubClient,
  args: {
    thread_id: string;
    branch_name?: string;
    title: string;
    body: string;
    files: FileChange[];
  },
  emitThreadUpdate?: ThreadUpdateEmitter
) {
  // 1. Fetch thread to get repo info
  const thread = await api.getThread(args.thread_id);
  const [owner, repo] = thread.repo.split('/');

  if (!owner || !repo) {
    return {
      content: [
        {
          type: 'text' as const,
          text: `Error: Thread repo "${thread.repo}" is not in "owner/repo" format.`,
        },
      ],
      isError: true,
    };
  }

  // If this is a revision iteration, force a new branch name
  if (thread.iteration_type === 'revision' && (!args.branch_name || !args.branch_name.includes('revision'))) {
    args.branch_name = `yocoolab/revision-${thread.iteration_number || 'new'}`;
  }

  // Pre-flight: gather full parent context for iterations
  let parentContext = '';
  if (thread.parent_thread_id && thread.parent_thread) {
    const parent = thread.parent_thread;
    const parentMessages = parent.messages || [];
    if (parentMessages.length > 0) {
      parentContext = [
        `## Context from parent thread`,
        ``,
        `**Original request:** ${parent.first_message_content || 'N/A'}`,
        `**Parent status:** ${parent.status}`,
        parent.pr_url ? `**Previous PR:** ${parent.pr_url}` : '',
        ``,
        `### Conversation history:`,
        ``,
        ...parentMessages.map(m => `**${m.author_name}:** ${m.content.substring(0, 200)}${m.content.length > 200 ? '...' : ''}`),
        ``,
      ].filter(Boolean).join('\n');
    }
  }

  const repoFullName = `${owner}/${repo}`;

  // 2. Check for an existing active working branch
  let workingBranch = await api.getWorkingBranch(repoFullName);

  // If working branch exists but its PR was closed/merged, mark it and create a new one
  if (workingBranch && workingBranch.pr_number) {
    try {
      const prOpen = await github.isPullRequestOpen(owner, repo, workingBranch.pr_number);
      if (!prOpen) {
        await api.updateWorkingBranch(workingBranch.id, { status: 'closed' });
        workingBranch = null;
      }
    } catch {
      // If we can't check, assume it's still valid
    }
  }

  let prNumber: number;
  let prUrl: string;
  let prBranch: string;
  let commitSha: string;
  let workingBranchId: string;

  if (!workingBranch) {
    // === FIRST FIX: Create working branch + PR ===
    const branchName = args.branch_name || 'yocoolab/feedback';
    const baseBranch = thread.branch || 'main';

    // Create the branch on GitHub
    const branchAlreadyExists = await github.branchExists(owner, repo, branchName);

    if (branchAlreadyExists) {
      // Branch exists but no working branch record — commit to it
      const commitResult = await github.commitToExistingBranch(
        owner, repo, branchName,
        `fix: ${args.title}\n\nAddresses feedback thread ${args.thread_id}`,
        args.files
      );
      commitSha = commitResult.commit_sha;

      // Create a PR if one doesn't exist
      const pr = await github.createPullRequest(
        owner, repo, branchName,
        'Yocoolab Feedback Fixes',
        buildInitialPrBody(repoFullName, args.thread_id, args.title, commitSha, parentContext),
        [], // No files — they're already committed
        baseBranch
      );
      prNumber = pr.pr_number;
      prUrl = pr.pr_url;
      prBranch = branchName;
    } else {
      // Create branch, commit files, and create PR in one shot
      const pr = await github.createPullRequest(
        owner, repo, branchName,
        'Yocoolab Feedback Fixes',
        '', // Body will be set after we know the commit SHA
        args.files,
        baseBranch
      );
      prNumber = pr.pr_number;
      prUrl = pr.pr_url;
      prBranch = branchName;

      // Get the commit SHA from the new branch
      const ref = await github.branchExists(owner, repo, branchName);
      commitSha = ''; // We'll get it from the PR
      try {
        const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/ref/heads/${branchName}`, {
          headers: { 'Authorization': `Bearer ${process.env.GITHUB_TOKEN}` },
        });
        const data = await response.json() as any;
        commitSha = data.object?.sha || '';
      } catch { /* ok */ }

      // Update PR body with the fix info
      const body = buildInitialPrBody(repoFullName, args.thread_id, args.title, commitSha, parentContext);
      await github.updatePullRequestBody(owner, repo, prNumber, body);
    }

    // Register the working branch in the backend
    const wb = await api.createWorkingBranch({
      repo: repoFullName,
      base_branch: baseBranch,
      branch_name: branchName,
      head_sha: commitSha,
      pr_number: prNumber,
      pr_url: prUrl,
      description: args.title,
    });
    workingBranchId = wb.id;

  } else {
    // === SUBSEQUENT FIX: Commit to existing working branch ===
    prNumber = workingBranch.pr_number!;
    prUrl = workingBranch.pr_url!;
    prBranch = workingBranch.branch_name;

    // Commit the files to the existing branch
    const commitResult = await github.commitToExistingBranch(
      owner, repo, workingBranch.branch_name,
      `fix: ${args.title}\n\nAddresses feedback thread ${args.thread_id}`,
      args.files
    );
    commitSha = commitResult.commit_sha;

    // Update the PR description with the new fix
    const currentBody = await github.getPullRequestBody(owner, repo, prNumber);
    const newFixNumber = workingBranch.thread_count + 1;
    const updatedBody = appendFixToPrBody(
      currentBody, repoFullName, newFixNumber,
      args.thread_id, args.title, commitSha
    );
    await github.updatePullRequestBody(owner, repo, prNumber, updatedBody);

    // Update working branch record with latest fix description
    const prevDesc = workingBranch.description || '';
    const newDesc = newFixNumber <= 2
      ? (prevDesc ? `${prevDesc}, ${args.title}` : args.title)
      : `${prevDesc.split(',')[0].trim()} + ${newFixNumber - 1} more`;
    await api.updateWorkingBranch(workingBranch.id, {
      head_sha: commitSha,
      thread_count: newFixNumber,
      description: newDesc,
    });
    workingBranchId = workingBranch.id;
  }

  // 3. Update thread with PR info and fix tracking
  await api.updateThread(args.thread_id, thread.repo, {
    pr_number: prNumber,
    pr_url: prUrl,
    pr_branch: prBranch,
    fix_commit_sha: commitSha,
    working_branch_id: workingBranchId,
  });

  // 4. Compute the preview URL from the GitHub Pages convention
  //    Pattern: https://{owner}.github.io/{repo}/pr-preview/pr-{number}/
  const previewUrl = `https://${owner.toLowerCase()}.github.io/${repo}/pr-preview/pr-${prNumber}/`;

  // 5. Register general preview URL pattern so extension recognizes ALL PR previews
  const generalPreviewPattern = `https://${owner.toLowerCase()}.github.io/${repo}/pr-preview/**`;
  try {
    await api.registerRepoUrl({
      repo: repoFullName,
      url_pattern: generalPreviewPattern,
      environment: 'staging',
      description: 'PR preview deploys',
    });
  } catch { /* non-fatal */ }

  // 6. Notify participants (include preview URL)
  await api.notifyParticipants(
    args.thread_id,
    thread.repo,
    'pr_created',
    `PR #${prNumber} updated with fix: ${args.title}\n\nPreview: ${previewUrl}`,
    prUrl
  );

  // 7. Push SSE event to extension (include preview URL)
  if (emitThreadUpdate) {
    emitThreadUpdate(args.thread_id, 'pr_created', {
      pr_number: prNumber,
      pr_url: prUrl,
      pr_branch: prBranch,
      commit_sha: commitSha,
      preview_url: previewUrl,
    });
  }

  const responseLines = [
    `PR created successfully!`,
    ``,
    `**PR #${prNumber}:** ${args.title}`,
    `**URL:** ${prUrl}`,
    `**Branch:** ${prBranch}`,
    `**Files changed:** ${args.files.length}`,
    ``,
    `**Preview:** ${previewUrl}`,
    `_(Preview deploys automatically via GitHub Actions — allow ~60s after push)_`,
    ``,
    `Thread participants have been notified.`,
  ];

  // Include parent context in response so Claude Code has full picture
  if (parentContext) {
    responseLines.push(``, `---`, ``, parentContext);
  }

  return {
    content: [
      {
        type: 'text' as const,
        text: responseLines.join('\n'),
      },
    ],
  };
}
